export const PAGE_MODE_LIST = "PAGE_MODE_LIST";
export const PAGE_MODE_FORM = "PAGE_MODE_FORM";
export const API = "API";
export const API_START = "API_START";
export const API_END = "API_END";
export const ACCESS_DENIED = "ACCESS_DENIED";
export const API_ERROR = "API_ERROR";

export const GET_DATA_ANGGOTA = "GET_DATA_ANGGOTA";
export const SET_DATA_ANGGOTA = "SET_DATA_ANGGOTA";
export const GET_LIST_ANGGOTA = "GET_LIST_ANGGOTA";
export const SET_LIST_ANGGOTA = "SET_LIST_ANGGOTA";
export const SET_ADD_ANGGOTA = "SET_ADD_ANGGOTA";
export const SET_EDIT_ANGGOTA = "SET_EDIT_ANGGOTA";
export const SAVE_ANGGOTA = "SAVE_ANGGOTA";
export const DELETE_ANGGOTA = "DELETE_ANGGOTA";
export const BACK_TO_LIST_ANGGOTA = "BACK_TO_LIST_ANGGOTA";

export const GET_DATA_PENGARANG = "GET_DATA_PENGARANG";
export const SET_DATA_PENGARANG = "SET_DATA_PENGARANG";
export const GET_LIST_PENGARANG = "GET_LIST_PENGARANG";
export const SET_LIST_PENGARANG = "SET_LIST_PENGARANG";
export const SET_ADD_PENGARANG = "SET_ADD_PENGARANG";
export const SET_EDIT_PENGARANG = "SET_EDIT_PENGARANG";
export const SAVE_PENGARANG = "SAVE_PENGARANG";
export const DELETE_PENGARANG = "DELETE_PENGARANG";
export const BACK_TO_LIST_PENGARANG = "BACK_TO_LIST_PENGARANG";

export const GET_DATA_PENERBIT = "GET_DATA_PENERBIT";
export const SET_DATA_PENERBIT = "SET_DATA_PENERBIT";
export const GET_LIST_PENERBIT = "GET_LIST_PENERBIT";
export const SET_LIST_PENERBIT = "SET_LIST_PENERBIT";
export const SET_ADD_PENERBIT = "SET_ADD_PENERBIT";
export const SET_EDIT_PENERBIT = "SET_EDIT_PENERBIT";
export const SAVE_PENERBIT = "SAVE_PENERBIT";
export const DELETE_PENERBIT = "DELETE_PENERBIT";
export const BACK_TO_LIST_PENERBIT = "BACK_TO_LIST_PENERBIT";

export const GET_DATA_RAK = "GET_DATA_RAK";
export const SET_DATA_RAK = "SET_DATA_RAK";
export const GET_LIST_RAK = "GET_LIST_RAK";
export const SET_LIST_RAK = "SET_LIST_RAK";
export const SET_ADD_RAK = "SET_ADD_RAK";
export const SET_EDIT_RAK = "SET_EDIT_RAK";
export const SAVE_RAK = "SAVE_RAK";
export const DELETE_RAK = "DELETE_RAK";
export const BACK_TO_LIST_RAK = "BACK_TO_LIST_RAK";

export const GET_DATA_BUKU = "GET_LIST_BUKU";
export const SET_DATA_BUKU = "SET_DATA_BUKU";
export const GET_LIST_BUKU = "GET_LIST_BUKU";
export const SET_LIST_BUKU = "SET_LIST_BUKU";
export const SET_ADD_BUKU = "SET_ADD_BUKU";
export const SET_EDIT_BUKU = "SET_EDIT_BUKU";
export const SAVE_BUKU = "SAVE_BUKU";
export const DELETE_BUKU = "DELETE_BUKU";
export const BACK_TO_LIST_BUKU = "BACK_TO_LIST_BUKU";

export const GET_DATA_PEMINJAMAN = "GET_DATA_PEMINJAMAN";
export const SET_DATA_PEMINJAMAN = "SET_DATA_PEMINJAMAN";
export const GET_LIST_PEMINJAMAN = "GET_LIST_PEMINJAMAN";
export const SET_LIST_PEMINJAMAN = "SET_LIST_PEMINJAMAN";
export const SET_ADD_PEMINJAMAN = "SET_ADD_PEMINJAMAN";
export const SET_EDIT_PEMINJAMAN = "SET_EDIT_PEMINJAMAN";
export const SET_PENGEMBALIAN = "SET_PENGEMBALIAN";
export const SAVE_PEMINJAMAN = "SAVE_PEMINJAMAN";
export const DELETE_PEMINJAMAN = "DELETE_PEMINJAMAN";
export const BACK_TO_LIST_PEMINJAMAN = "BACK_TO_LIST_PEMINJAMAN";

export const GET_DATA_PENGEMBALIAN = "GET_DATA_PENGEMBALIAN";
export const SET_DATA_PENGEMBALIAN = "SET_DATA_PENGEMBALIAN";
export const GET_LIST_PENGEMBALIAN = "GET_LIST_PENGEMBALIAN";
export const SET_LIST_PENGEMBALIAN = "SET_LIST_PENGEMBALIAN";
export const SET_ADD_PENGEMBALIAN = "SET_ADD_PENGEMBALIAN";
export const SET_EDIT_PENGEMBALIAN = "SET_EDIT_PENGEMBALIAN";
export const SAVE_PENGEMBALIAN = "SAVE_PENGEMBALIAN";
export const DELETE_PENGEMBALIAN = "DELETE_PENGEMBALIAN";
export const BACK_TO_LIST_PENGEMBALIAN = "BACK_TO_LIST_PENGEMBALIAN";